# Data Science/ Analytics Intern – Round-0 Assignment (Trader Performance vs Market Sentiment)

#Objective: Analyze how market sentiment (Fear/Greed) relates to trader behavior and performance on Hyperliquid. Your goal is to uncover patterns that could inform smarter trading strategies.

In [186]:
# Importing the libraries which are required: 
# Also, the libraries which are required and I hae used particularly are written in requirements.txt  
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

Sub-Part 01:

In [187]:
#Loading the datasets and framing them as dataframe.

# dataframe from fear_greed_index.csv
df_0 = pd.read_csv('fear_greed_index.csv') 

# dataframe from historical_data.csv
df_1 = pd.read_csv('historical_data.csv')

In [188]:
df_0

       timestamp  value classification        date
0     1517463000     30           Fear  2018-02-01
1     1517549400     15   Extreme Fear  2018-02-02
2     1517635800     40           Fear  2018-02-03
3     1517722200     24   Extreme Fear  2018-02-04
4     1517808600     11   Extreme Fear  2018-02-05
...          ...    ...            ...         ...
2639  1745818200     54        Neutral  2025-04-28
2640  1745904600     60          Greed  2025-04-29
2641  1745991000     56          Greed  2025-04-30
2642  1746077400     53        Neutral  2025-05-01
2643  1746163800     67          Greed  2025-05-02

[2644 rows x 4 columns]

In [189]:
df_1

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211219,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,382.20,420.80,SELL,25-04-2025 15:35,7546.600000,Close Long,-20.2566,0xcd339c08dc7b615a993c0422374d8e02027400092bc2...,88803313862,False,0.042080,1.990000e+14,1.750000e+12
211220,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,2124.10,2338.63,SELL,25-04-2025 15:35,7164.400000,Close Long,-112.5773,0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...,88803313862,False,0.233863,9.260000e+14,1.750000e+12
211221,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,423.40,466.16,SELL,25-04-2025 15:35,5040.300000,Close Long,-22.4402,0x0780085b0c0a943eea800422374d920204c100edf579...,88803313862,False,0.046616,6.930000e+14,1.750000e+12
211222,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,3599.80,3963.38,SELL,25-04-2025 15:35,4616.900000,Close Long,-190.7894,0x349c29934913b25c89e20422374d920204cd008b8a0e...,88803313862,False,0.396337,4.180000e+14,1.750000e+12
211223,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,1017.10,1119.83,SELL,25-04-2025 15:35,1017.100000,Close Long,-53.9063,0xac77fab973c455d77a670422374d9602039800f1f78c...,88803313862,False,0.111982,3.270000e+14,1.750000e+12

Inspecting both the datasets:

Performing EDA:

In [190]:
df_0.head() # Showcasing top 5 elements

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [191]:
df_1.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [192]:
df_0.shape  # 2644 rows and 4 columns in this dataset.

(2644, 4)

In [193]:
df_1.shape  # 211224 rows and 16 columns

(211224, 16)

In [194]:
df_0.columns

Index(['timestamp', 'value', 'classification', 'date'], dtype='object')

In [195]:
df_1.columns

Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp'],
      dtype='object')

In [196]:
df_0.info

<bound method DataFrame.info of        timestamp  value classification        date
0     1517463000     30           Fear  2018-02-01
1     1517549400     15   Extreme Fear  2018-02-02
2     1517635800     40           Fear  2018-02-03
3     1517722200     24   Extreme Fear  2018-02-04
4     1517808600     11   Extreme Fear  2018-02-05
...          ...    ...            ...         ...
2639  1745818200     54        Neutral  2025-04-28
2640  1745904600     60          Greed  2025-04-29
2641  1745991000     56          Greed  2025-04-30
2642  1746077400     53        Neutral  2025-05-01
2643  1746163800     67          Greed  2025-05-02

[2644 rows x 4 columns]>

In [197]:
df_1.info

<bound method DataFrame.info of                                            Account      Coin  Execution Price  \
0       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9769
1       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9800
2       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9855
3       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9874
4       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9894
...                                            ...       ...              ...
211219  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211220  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211221  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211222  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211223  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010

        Size Tokens  Size USD  Side     Timestamp IST  Start Position  \
0            986.87   7872.16   BUY  02-12-2024 22:50        0.000000
1             16.00    127.68   BUY  02-12-2024 22:50      986.524596
2            144.09   1150.63   BUY  02-12-2024 22:50     1002.518996
3            142.98   1142.04   BUY  02-12-2024 22:50     1146.558564
4              8.73     69.75   BUY  02-12-2024 22:50     1289.488521
...             ...       ...   ...               ...             ...
211219       382.20    420.80  SELL  25-04-2025 15:35     7546.600000
211220      2124.10   2338.63  SELL  25-04-2025 15:35     7164.400000
211221       423.40    466.16  SELL  25-04-2025 15:35     5040.300000
211222      3599.80   3963.38  SELL  25-04-2025 15:35     4616.900000
211223      1017.10   1119.83  SELL  25-04-2025 15:35     1017.100000

         Direction  Closed PnL  \
0              Buy      0.0000
1              Buy      0.0000
2              Buy      0.0000
3              Buy      0.0000
4              Buy      0.0000
...            ...         ...
211219  Close Long    -20.2566
211220  Close Long   -112.5773
211221  Close Long    -22.4402
211222  Close Long   -190.7894
211223  Close Long    -53.9063

                                         Transaction Hash     Order ID  \
0       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
1       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
2       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
3       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
4       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
...                                                   ...          ...
211219  0xcd339c08dc7b615a993c0422374d8e02027400092bc2...  88803313862
211220  0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...  88803313862
211221  0x0780085b0c0a943eea800422374d920204c100edf579...  88803313862
211222  0x349c29934913b25c89e20422374d920204cd008b8a0e...  88803313862
211223  0xac77fab973c455d77a670422374d9602039800f1f78c...  88803313862

        Crossed       Fee      Trade ID     Timestamp
0          True  0.345404  8.950000e+14  1.730000e+12
1          True  0.005600  4.430000e+14  1.730000e+12
2          True  0.050431  6.600000e+14  1.730000e+12
3          True  0.050043  1.080000e+15  1.730000e+12
4          True  0.003055  1.050000e+15  1.730000e+12
...         ...       ...           ...           ...
211219    False  0.042080  1.990000e+14  1.750000e+12
211220    False  0.233863  9.260000e+14  1.750000e+12
211221    False  0.046616  6.930000e+14  1.750000e+12
211222    False  0.396337  4.180000e+14  1.750000e+12
211223    False  0.111982  3.270000e+14  1.750000e+12

[211224 rows x 16 columns]>

In [198]:
# Checking for any missing or null values: 
df_0.isnull()

      timestamp  value  classification   date
0         False  False           False  False
1         False  False           False  False
2         False  False           False  False
3         False  False           False  False
4         False  False           False  False
...         ...    ...             ...    ...
2639      False  False           False  False
2640      False  False           False  False
2641      False  False           False  False
2642      False  False           False  False
2643      False  False           False  False

[2644 rows x 4 columns]

In [199]:
df_0.isnull().value_counts() 

# we don't have any missing data or value for this first dataset.

timestamp  value  classification  date
False      False  False           False    2644
Name: count, dtype: int64

In [200]:
df_1.isnull()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211219,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
211220,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
211221,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
211222,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
211223,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [201]:
df_1.isnull().value_counts().sum()

# Neither this one consist any null or missing values. Good to go

np.int64(211224)

In [202]:
# Checking for duplicated values for firt dataframe:
df_0.duplicated().sum() # No, we don't even have any dulicated values for this dataset.

np.int64(0)

In [203]:
# checking for any duplicated values for another dataframe:
df_1.duplicated().sum() # None

np.int64(0)

Till now, I have performed some basic operations in order to extract the overall insight of the given dataframes.

Sub-part 2: Convert timestamps and align the datasets by date.

In [204]:

# ── df_1 = Hyperliquid Trader Data, I have changed this using to_datetime()
df_1['date'] = pd.to_datetime(
    df_1['Timestamp IST'], 
    format='%d-%m-%Y %H:%M'
).dt.strftime('%Y-%m-%d')

# ── df_0 = Fear/Greed Data
df_0['date'] = pd.to_datetime(
    df_0['timestamp'], 
    unit='s'
).dt.strftime('%Y-%m-%d')

In [205]:
# Verifying for fear_greed df.
df_0[['timestamp', 'date']].head(3)

    timestamp        date
0  1517463000  2018-02-01
1  1517549400  2018-02-02
2  1517635800  2018-02-03

In [206]:
# Verifying for second one.
df_1[['Timestamp IST', 'date']].head(3)

      Timestamp IST        date
0  02-12-2024 22:50  2024-12-02
1  02-12-2024 22:50  2024-12-02
2  02-12-2024 22:50  2024-12-02

In [207]:
# Perfroming the alignment for the dataset. Merging the dataset.
merged = pd.merge(
    df_1,
    df_0[['date', 'value', 'classification']],
    on='date',
    how='left'
)

In [208]:
merged.head(2)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,date,value,classification
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed

Sub-part 03: 
Create the key metrics you will analyze, for example:
* daily PnL per trader (or per account)
* win rate, average trade size
* leverage distribution
* number of trades per day
* long/short ratio

In [209]:
df_1.head(2)

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,date
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2024-12-02

In [210]:
# Daily PnL per trader, On the basis of date and account, I have found some features.
daily_metrics = df_1.groupby(['date', 'Account']).agg(
    daily_pnl      = ('Closed PnL',  'sum'),
    num_trades     = ('Closed PnL',  'count'),
    avg_trade_size = ('Size USD',       'mean'),
    win_trades     = ('Closed PnL',  lambda x: (x > 0).sum()),
).reset_index()

daily_metrics.head()

,date,Account,daily_pnl,num_trades,avg_trade_size,win_trades
0,2023-05-01,0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891,0.000000,3,159.000000,0
1,2023-12-05,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,0.000000,9,5556.203333,0
2,2023-12-14,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,-205.434737,11,10291.213636,4
3,2023-12-15,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,-24.632034,2,5304.975000,0
4,2023-12-16,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,0.000000,3,5116.256667,0

In [211]:
# Win rate
daily_metrics['win_rate'] = daily_metrics['win_trades'] / daily_metrics['num_trades']

#Show
daily_metrics['win_rate']

0       0.000000
1       0.000000
2       0.363636
3       0.000000
4       0.000000
          ...
2336    0.350694
2337    0.780822
2338    1.000000
2339    0.008621
2340    0.328244
Name: win_rate, Length: 2341, dtype: float64

In [212]:
# Long/Short ratio
ls = df_1.groupby(['date', 'Account'])['Side'].value_counts().unstack(fill_value=0)
ls['long_short_ratio'] = ls.get('Buy', 0) / ls.get('Sell', 1)
daily_metrics = daily_metrics.merge(ls[['long_short_ratio']], on=['date', 'Account'], how='left')

daily_metrics.head()

,date,Account,daily_pnl,num_trades,avg_trade_size,win_trades,win_rate,long_short_ratio
0,2023-05-01,0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891,0.000000,3,159.000000,0,0.000000,0.0
1,2023-12-05,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,0.000000,9,5556.203333,0,0.000000,0.0
2,2023-12-14,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,-205.434737,11,10291.213636,4,0.363636,0.0
3,2023-12-15,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,-24.632034,2,5304.975000,0,0.000000,0.0
4,2023-12-16,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,0.000000,3,5116.256667,0,0.000000,0.0

For leverage — since it's not in your data, just add a note in your notebook:
* leverage column not present in this dataset
* leverage distribution analysis will be skipped
* or approximated using position size / account balance if available

# Part B:  Analysis

Some pre required setups:

In [213]:
merged_df = pd.merge(
    daily_metrics,
    df_0[['date', 'value', 'classification']],
    on='date',
    how='left'
)

In [214]:
q1 = merged_df.groupby('classification').agg(
    avg_daily_pnl  = ('daily_pnl',  'mean'),
    avg_win_rate   = ('win_rate',   'mean'),
    avg_trades     = ('num_trades', 'mean'),
    avg_loss_days  = ('daily_pnl',  lambda x: x[x < 0].mean())
).reset_index()

q1

  classification  avg_daily_pnl  avg_win_rate  avg_trades  avg_loss_days
0   Extreme Fear    4619.439053      0.329659  133.750000  -15534.761937
1  Extreme Greed    5161.922644      0.386387   76.030418   -6109.737110
2           Fear    5328.818161      0.364033   98.153968   -6071.371829
3          Greed    3318.100730      0.343559   77.628086  -16562.519710
4        Neutral    3438.618818      0.355414  100.228723   -6879.440610

In [215]:
#Trade Direction Counts
ls_ratio = merged.groupby(
    ['date', 'Account', 'Side']
).size().unstack(fill_value=0)

In [216]:
# Create Ratio
ls_ratio['long_short_ratio'] = (
    (ls_ratio.get('Buy', 0) + 1)
    /
    (ls_ratio.get('Sell', 0) + 1)
)

In [217]:
#Merging into daily metrics
daily_metrics = daily_metrics.merge(
    ls_ratio['long_short_ratio'],
    on=['date', 'Account'],
    how='left'
)

In [218]:
merged.rename(columns={
    'classification': 'Sentiment'
}, inplace=True)

In [219]:
daily_metrics = daily_metrics.sort_values(
    ['Account', 'date']
)

daily_metrics['cum_pnl'] = (
    daily_metrics.groupby('Account')['daily_pnl']
    .cumsum()
)

daily_metrics['rolling_max'] = (
    daily_metrics.groupby('Account')['cum_pnl']
    .cummax()
)

daily_metrics['drawdown'] = (
    daily_metrics['cum_pnl']
    - daily_metrics['rolling_max']
)

Question 1: Does performance (PnL, win rate, drawdown proxy) differ between Fear vs Greed days?