# Data Science/ Analytics Intern – Round-0 Assignment (Trader Performance vs Market Sentiment)

#Objective: Analyze how market sentiment (Fear/Greed) relates to trader behavior and performance on Hyperliquid. Your goal is to uncover patterns that could inform smarter trading strategies.

In [3]:
# Importing the libraries which are required: 
# Also, the libraries which are required and I hae used particularly are written in requirements.txt  
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [6]:
#Loading the datasets and framing them as dataframe.

# dataframe from fear_greed_index.csv
df_0 = pd.read_csv('fear_greed_index.csv') 

# dataframe from historical_data.csv
df_1 = pd.read_csv('historical_data.csv')

In [ ]:
df_0

       timestamp  value classification        date
0     1517463000     30           Fear  2018-02-01
1     1517549400     15   Extreme Fear  2018-02-02
2     1517635800     40           Fear  2018-02-03
3     1517722200     24   Extreme Fear  2018-02-04
4     1517808600     11   Extreme Fear  2018-02-05
...          ...    ...            ...         ...
2639  1745818200     54        Neutral  2025-04-28
2640  1745904600     60          Greed  2025-04-29
2641  1745991000     56          Greed  2025-04-30
2642  1746077400     53        Neutral  2025-05-01
2643  1746163800     67          Greed  2025-05-02

[2644 rows x 4 columns]

In [8]:
df_1

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0000,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211219,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,382.20,420.80,SELL,25-04-2025 15:35,7546.600000,Close Long,-20.2566,0xcd339c08dc7b615a993c0422374d8e02027400092bc2...,88803313862,False,0.042080,1.990000e+14,1.750000e+12
211220,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,2124.10,2338.63,SELL,25-04-2025 15:35,7164.400000,Close Long,-112.5773,0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...,88803313862,False,0.233863,9.260000e+14,1.750000e+12
211221,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,423.40,466.16,SELL,25-04-2025 15:35,5040.300000,Close Long,-22.4402,0x0780085b0c0a943eea800422374d920204c100edf579...,88803313862,False,0.046616,6.930000e+14,1.750000e+12
211222,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,3599.80,3963.38,SELL,25-04-2025 15:35,4616.900000,Close Long,-190.7894,0x349c29934913b25c89e20422374d920204cd008b8a0e...,88803313862,False,0.396337,4.180000e+14,1.750000e+12
211223,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.1010,1017.10,1119.83,SELL,25-04-2025 15:35,1017.100000,Close Long,-53.9063,0xac77fab973c455d77a670422374d9602039800f1f78c...,88803313862,False,0.111982,3.270000e+14,1.750000e+12

Inspecting both the datasets:

Performing EDA:

In [ ]:
df_0.head() # Showcasing top 5 elements

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [ ]:
df_1.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [ ]:
df_0.shape  # 2644 rows and 4 columns in this dataset.

(2644, 4)

In [14]:
df_1.shape  # 211224 rows and 16 columns

(211224, 16)

In [15]:
df_0.columns

Index(['timestamp', 'value', 'classification', 'date'], dtype='object')

In [16]:
df_1.columns

Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp'],
      dtype='object')

In [17]:
df_0.info

<bound method DataFrame.info of        timestamp  value classification        date
0     1517463000     30           Fear  2018-02-01
1     1517549400     15   Extreme Fear  2018-02-02
2     1517635800     40           Fear  2018-02-03
3     1517722200     24   Extreme Fear  2018-02-04
4     1517808600     11   Extreme Fear  2018-02-05
...          ...    ...            ...         ...
2639  1745818200     54        Neutral  2025-04-28
2640  1745904600     60          Greed  2025-04-29
2641  1745991000     56          Greed  2025-04-30
2642  1746077400     53        Neutral  2025-05-01
2643  1746163800     67          Greed  2025-05-02

[2644 rows x 4 columns]>

In [19]:
df_1.info

<bound method DataFrame.info of                                            Account      Coin  Execution Price  \
0       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9769
1       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9800
2       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9855
3       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9874
4       0xae5eacaf9c6b9111fd53034a602c192a04e082ed      @107           7.9894
...                                            ...       ...              ...
211219  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211220  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211221  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211222  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010
211223  0x72743ae2822edd658c0c50608fd7c5c501b2afbd  FARTCOIN           1.1010

        Size Tokens  Size USD  Side     Timestamp IST  Start Position  \
0            986.87   7872.16   BUY  02-12-2024 22:50        0.000000
1             16.00    127.68   BUY  02-12-2024 22:50      986.524596
2            144.09   1150.63   BUY  02-12-2024 22:50     1002.518996
3            142.98   1142.04   BUY  02-12-2024 22:50     1146.558564
4              8.73     69.75   BUY  02-12-2024 22:50     1289.488521
...             ...       ...   ...               ...             ...
211219       382.20    420.80  SELL  25-04-2025 15:35     7546.600000
211220      2124.10   2338.63  SELL  25-04-2025 15:35     7164.400000
211221       423.40    466.16  SELL  25-04-2025 15:35     5040.300000
211222      3599.80   3963.38  SELL  25-04-2025 15:35     4616.900000
211223      1017.10   1119.83  SELL  25-04-2025 15:35     1017.100000

         Direction  Closed PnL  \
0              Buy      0.0000
1              Buy      0.0000
2              Buy      0.0000
3              Buy      0.0000
4              Buy      0.0000
...            ...         ...
211219  Close Long    -20.2566
211220  Close Long   -112.5773
211221  Close Long    -22.4402
211222  Close Long   -190.7894
211223  Close Long    -53.9063

                                         Transaction Hash     Order ID  \
0       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
1       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
2       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
3       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
4       0xec09451986a1874e3a980418412fcd0201f500c95bac...  52017706630
...                                                   ...          ...
211219  0xcd339c08dc7b615a993c0422374d8e02027400092bc2...  88803313862
211220  0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...  88803313862
211221  0x0780085b0c0a943eea800422374d920204c100edf579...  88803313862
211222  0x349c29934913b25c89e20422374d920204cd008b8a0e...  88803313862
211223  0xac77fab973c455d77a670422374d9602039800f1f78c...  88803313862

        Crossed       Fee      Trade ID     Timestamp
0          True  0.345404  8.950000e+14  1.730000e+12
1          True  0.005600  4.430000e+14  1.730000e+12
2          True  0.050431  6.600000e+14  1.730000e+12
3          True  0.050043  1.080000e+15  1.730000e+12
4          True  0.003055  1.050000e+15  1.730000e+12
...         ...       ...           ...           ...
211219    False  0.042080  1.990000e+14  1.750000e+12
211220    False  0.233863  9.260000e+14  1.750000e+12
211221    False  0.046616  6.930000e+14  1.750000e+12
211222    False  0.396337  4.180000e+14  1.750000e+12
211223    False  0.111982  3.270000e+14  1.750000e+12

[211224 rows x 16 columns]>

In [20]:
# Checking for any missing or null values: 
df_0.isnull()

      timestamp  value  classification   date
0         False  False           False  False
1         False  False           False  False
2         False  False           False  False
3         False  False           False  False
4         False  False           False  False
...         ...    ...             ...    ...
2639      False  False           False  False
2640      False  False           False  False
2641      False  False           False  False
2642      False  False           False  False
2643      False  False           False  False

[2644 rows x 4 columns]

In [ ]:
df_0.isnull().value_counts() 

# we don't have any missing data or value for this first dataset.

timestamp  value  classification  date
False      False  False           False    2644
Name: count, dtype: int64

In [24]:
df_1.isnull()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211219,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
211220,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
211221,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
211222,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
211223,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [37]:
df_1.isnull().value_counts().sum()

# Neither this one consist any null or missing values. Good to go

np.int64(211224)

In [ ]:
# Checking for duplicated values for firt dataframe:
df_0.duplicated().sum() # No, we don't even have any dulicated values for this dataset.

np.int64(0)

In [ ]:
# checking for any duplicated values for another dataframe:
df_1.duplicated().sum() # None

np.int64(0)